import {Injectable} from '@angular/core';

@Injectable()
export class AppInfoService {
  movies = [{
    title: 'The Dark Knight',
    year: '2008',
    genres: ['Action', 'Crime', 'Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT152M',
    releaseDate: '2008-07-25',
    avgRate: 0,
    originalTitle: '',
    storyline: 'Set within a year after the events of Batman Begins, Batman, Lieutenant James Gordon, and new district attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City until a mysterious and sadistic criminal mastermind known only as the Joker appears in Gotham, creating a new wave of chaos. Batman\'s struggle against the Joker becomes deeply personal, forcing him to "confront everything he believes" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent and Rachel Dawes.                Written by\nLeon Lombardi',
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    imdbRating: 9,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg',
    id: 1
  }, {
    title: '12 edsvurna män',
    year: '1957',
    genres: ['Crime', 'Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SY500_CR0,0,333,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT96M',
    releaseDate: '1957-07-29',
    avgRate: 0,
    originalTitle: '12 Angry Men',
    storyline: 'The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors\' prejudices and preconceptions about the trial, the accused, and each other. Based on the play, all of the action takes place on the stage of the jury room.                Written by\npjk <PETESID@VNET.IBM.COM>',
    actors: ['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam'],
    imdbRating: 8.9,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BODQwOTc5MDM2N15BMl5BanBnXkFtZTcwODQxNTEzNA@@._V1_SY500_CR0,0,333,500_AL_.jpg',
    id: 2
  }, {
    title: 'Schindler\'s List',
    year: '1993',
    genres: ['Biography', 'Drama', 'History'],
    comments: {},
    ratings: {},
    poster: 'MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,333,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT195M',
    releaseDate: '1994-03-04',
    avgRate: 0,
    originalTitle: '',
    storyline: 'Oskar Schindler is a vainglorious and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.                Written by\nHarald Mayr <marvin@bike.augusta.de>',
    actors: ['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley'],
    imdbRating: 8.9,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,333,500_AL_.jpg',
    id: 3
  }, {
    title: 'Pulp Fiction',
    year: '1994',
    genres: ['Crime', 'Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SY500_CR0,0,336,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT154M',
    releaseDate: '1994-11-25',
    avgRate: 0,
    originalTitle: '',
    storyline: 'Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his weight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.                Written by\nSoumitra',
    actors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    imdbRating: 8.9,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SY500_CR0,0,336,500_AL_.jpg',
    id: 4
  }, {
    title: 'Sagan om konungens återkomst',
    year: '2003',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    comments: {},
    ratings: {},
    poster: 'MV5BYWY1ZWQ5YjMtMDE0MS00NWIzLWE1M2YtODYzYTk2OTNlYWZmXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX334_AL_.jpg',
    contentRating: '11',
    duration: 'PT201M',
    releaseDate: '2003-12-17',
    avgRate: 0,
    originalTitle: 'The Lord of the Rings: The Return of the King',
    storyline: 'The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Hobbits Frodo and Sam reach Mordor in their quest to destroy the "one ring", while Aragorn leads the forces of good against Sauron\'s evil army at the stone city of Minas Tirith.                Written by\nJwelch5742',
    actors: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
    imdbRating: 8.9,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYWY1ZWQ5YjMtMDE0MS00NWIzLWE1M2YtODYzYTk2OTNlYWZmXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX334_AL_.jpg',
    id: 5
  }, {
    title: 'Den gode, den onde, den fule',
    year: '1966',
    genres: ['Western'],
    comments: {},
    ratings: {},
    poster: 'MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_SY500_CR0,0,328,500_AL_.jpg',
    contentRating: '',
    duration: 'PT161M',
    releaseDate: '1968-04-10',
    avgRate: 0,
    originalTitle: 'Il buono, il brutto, il cattivo',
    storyline: 'Blondie (The Good) is a professional gunslinger who is out trying to earn a few dollars. Angel Eyes (The Bad) is a hit man who always commits to a task and sees it through, as long as he is paid to do so. And Tuco (The Ugly) is a wanted outlaw trying to take care of his own hide. Tuco and Blondie share a partnership together making money off Tuco\'s bounty, but when Blondie unties the partnership, Tuco tries to hunt down Blondie. When Blondie and Tuco come across a horse carriage loaded with dead bodies, they soon learn from the only survivor (Bill Carson) that he and a few other men have buried a stash of gold in a cemetery. Unfortunately Carson dies and Tuco only finds out the name of the cemetery, while Blondie finds out the name on the grave. Now the two must keep each other alive in order to find the gold. Angel Eyes (who had been looking for Bill Carson) discovers that Tuco and Blondie met with Carson and knows they know the location of the gold. All he needs is for the two to ...                Written by\nJeremy Thomson',
    actors: ['Clint Eastwood', 'Eli Wallach', 'Lee Van Cleef'],
    imdbRating: 8.9,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BOTQ5NDI3MTI4MF5BMl5BanBnXkFtZTgwNDQ4ODE5MDE@._V1_SY500_CR0,0,328,500_AL_.jpg',
    id: 6
  }, {
    title: 'Fight Club',
    year: '1999',
    genres: ['Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BZGY5Y2RjMmItNDg5Yy00NjUwLThjMTEtNDc2OGUzNTBiYmM1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX290_CR0,0,290,429_AL_.jpg',
    contentRating: '15',
    duration: 'PT139M',
    releaseDate: '1999-12-25',
    avgRate: 0,
    originalTitle: '',
    storyline: 'A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler\'s fight club, he must accept the awful truth that Tyler may not be who he says he is.                Written by\nRhiannon',
    actors: ['Brad Pitt', 'Edward Norton', 'Meat Loaf'],
    imdbRating: 8.8,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BZGY5Y2RjMmItNDg5Yy00NjUwLThjMTEtNDc2OGUzNTBiYmM1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX290_CR0,0,290,429_AL_.jpg',
    id: 7
  }, {
    title: 'Sagan om ringen: Härskarringen',
    year: '2001',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    comments: {},
    ratings: {},
    poster: 'MV5BNmFmZDdkODMtNzUyMy00NzhhLWFjZmEtMGMzYjNhMDA1NTBkXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX342_AL_.jpg',
    contentRating: '11',
    duration: 'PT178M',
    releaseDate: '2001-12-19',
    avgRate: 0,
    originalTitle: 'The Lord of the Rings: The Fellowship of the Ring',
    storyline: 'An ancient Ring thought lost for centuries has been found, and through a strange twist in fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it! However he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir and his three Hobbit friends Merry, Pippin and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign!                Written by\nPaul Twomey <toomsp@hotmail.com>',
    actors: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
    imdbRating: 8.8,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNmFmZDdkODMtNzUyMy00NzhhLWFjZmEtMGMzYjNhMDA1NTBkXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SY500_SX342_AL_.jpg',
    id: 8
  }, {
    title: 'Rymdimperiet slår tillbaka',
    year: '1980',
    genres: ['Action', 'Adventure', 'Fantasy'],
    comments: {},
    ratings: {},
    poster: 'MV5BYmViY2M2MTYtY2MzOS00YjQ1LWIzYmEtOTBiNjhlMGM0NjZjXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,322,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT124M',
    releaseDate: '1980-08-15',
    avgRate: 0,
    originalTitle: 'Star Wars: Episode V - The Empire Strikes Back',
    storyline: 'Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi master\'s help will Luke survive when the dark side of the Force beckons him into the ultimate duel with Darth Vader.                Written by\nJwelch5742',
    actors: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'],
    imdbRating: 8.8,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYmViY2M2MTYtY2MzOS00YjQ1LWIzYmEtOTBiNjhlMGM0NjZjXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,322,500_AL_.jpg',
    id: 9
  }, {
    title: 'Forrest Gump',
    year: '1994',
    genres: ['Comedy', 'Drama', 'Romance'],
    comments: {},
    ratings: {},
    poster: 'MV5BYThjM2MwZGMtMzg3Ny00NGRkLWE4M2EtYTBiNWMzOTY0YTI4XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,378,500_AL_.jpg',
    contentRating: '11',
    duration: 'PT142M',
    releaseDate: '1994-10-14',
    avgRate: 0,
    originalTitle: '',
    storyline: 'Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His \'mama\' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.                Written by\naliw135',
    actors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    imdbRating: 8.8,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYThjM2MwZGMtMzg3Ny00NGRkLWE4M2EtYTBiNWMzOTY0YTI4XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,378,500_AL_.jpg',
    id: 10
  }, {
    title: 'Inception',
    year: '2010',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    comments: {},
    ratings: {},
    poster: 'MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT148M',
    releaseDate: '2010-07-23',
    avgRate: 0,
    originalTitle: '',
    storyline: 'Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb\'s rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible - inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.                Written by\nWarner Bros. Pictures',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
    imdbRating: 8.8,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SY500_CR0,0,337,500_AL_.jpg',
    id: 11
  }, {
    title: 'Sagan om de två tornen',
    year: '2002',
    genres: ['Adventure', 'Drama', 'Fantasy'],
    comments: {},
    ratings: {},
    poster: 'MV5BMTAyNDU0NjY4NTheQTJeQWpwZ15BbWU2MDk4MTY2Nw@@._V1_SY256_SX175_AL_.jpg',
    contentRating: '11',
    duration: 'PT179M',
    releaseDate: '2002-12-18',
    avgRate: 0,
    originalTitle: 'The Lord of the Rings: The Two Towers',
    storyline: 'While Frodo and Sam, now accompanied by a new guide, continue their hopeless journey towards the land of shadow to destroy the One Ring, each member of the broken fellowship plays their part in the battle against the evil wizard Saruman and his armies of Isengard.',
    actors: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'],
    imdbRating: 8.7,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTAyNDU0NjY4NTheQTJeQWpwZ15BbWU2MDk4MTY2Nw@@._V1_SY256_SX175_AL_.jpg',
    id: 12
  }, {
    title: 'Gökboet',
    year: '1975',
    genres: ['Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY500_CR0,0,336,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT133M',
    releaseDate: '1976-02-26',
    avgRate: 0,
    originalTitle: 'One Flew Over the Cuckoo\'s Nest',
    storyline: 'McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse.                Written by\nJacob Oberfrank',
    actors: ['Jack Nicholson', 'Louise Fletcher', 'Michael Berryman'],
    imdbRating: 8.7,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY500_CR0,0,336,500_AL_.jpg',
    id: 13
  }, {
    title: 'Maffiabröder',
    year: '1990',
    genres: ['Biography', 'Crime', 'Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BNThjMzczMjctZmIwOC00NTQ4LWJhZWItZDdhNTk5ZTdiMWFlXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,334,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT146M',
    releaseDate: '1990-09-14',
    avgRate: 0,
    originalTitle: 'Goodfellas',
    storyline: 'Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners\' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?                Written by\nColin Tinto <cst@imdb.com>',
    actors: ['Robert De Niro', 'Ray Liotta', 'Joe Pesci'],
    imdbRating: 8.7,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNThjMzczMjctZmIwOC00NTQ4LWJhZWItZDdhNTk5ZTdiMWFlXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,334,500_AL_.jpg',
    id: 14
  }, {
    title: 'Matrix',
    year: '1999',
    genres: ['Action', 'Sci-Fi'],
    comments: {},
    ratings: {},
    poster: 'MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,332,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT136M',
    releaseDate: '1999-07-14',
    avgRate: 0,
    originalTitle: 'The Matrix',
    storyline: 'Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans\' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.                Written by\nredcommander27',
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    imdbRating: 8.7,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,332,500_AL_.jpg',
    id: 15
  }, {
    title: 'De sju samurajerna',
    year: '1954',
    genres: ['Adventure', 'Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BMTc5MDY1MjU5MF5BMl5BanBnXkFtZTgwNDM2OTE4MzE@._V1_SY500_CR0,0,356,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT207M',
    releaseDate: '1965-09-20',
    avgRate: 0,
    originalTitle: 'Shichinin no samurai',
    storyline: 'A veteran samurai, who has fallen on hard times, answers a village\'s request for protection from bandits. He gathers 6 other samurai to help him, and they teach the townspeople how to defend themselves, and they supply the samurai with three small meals a day. The film culminates in a giant battle when 40 bandits attack the village.                Written by\nColin Tinto <cst@imdb.com>',
    actors: ['Toshirô Mifune', 'Takashi Shimura', 'Keiko Tsushima'],
    imdbRating: 8.7,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5MDY1MjU5MF5BMl5BanBnXkFtZTgwNDM2OTE4MzE@._V1_SY500_CR0,0,356,500_AL_.jpg',
    id: 16
  }, {
    title: 'Stjärnornas krig',
    year: '1977',
    genres: ['Action', 'Adventure', 'Fantasy'],
    comments: {},
    ratings: {},
    poster: 'MV5BYzQ2OTk4N2QtOGQwNy00MmI3LWEwNmEtOTk0OTY3NDk2MGJkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY500_CR0,0,332,500_AL_.jpg',
    contentRating: '11',
    duration: 'PT121M',
    releaseDate: '1977-12-16',
    avgRate: 0,
    originalTitle: 'Star Wars',
    storyline: 'The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.                Written by\nJwelch5742',
    actors: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'],
    imdbRating: 8.7,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYzQ2OTk4N2QtOGQwNy00MmI3LWEwNmEtOTk0OTY3NDk2MGJkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY500_CR0,0,332,500_AL_.jpg',
    id: 17
  }, {
    title: 'Guds stad',
    year: '2002',
    genres: ['Crime', 'Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX200_CR0,0,200,296_AL_.jpg',
    contentRating: '15',
    duration: 'PT130M',
    releaseDate: '2003-10-17',
    avgRate: 0,
    originalTitle: 'Cidade de Deus',
    storyline: 'Brazil, 1960s, City of God. The Tender Trio robs motels and gas trucks. Younger kids watch and learn well...too well. 1970s: Li\'l Zé has prospered very well and owns the city. He causes violence and fear as he wipes out rival gangs without mercy. His best friend Bené is the only one to keep him on the good side of sanity. Rocket has watched these two gain power for years, and he wants no part of it. Yet he keeps getting swept up in the madness. All he wants to do is take pictures. 1980s: Things are out of control between the last two remaining gangs...will it ever end? Welcome to the City of God.                Written by\nJeff Mellinger <jeffmellinger@astound.net>',
    actors: ['Alexandre Rodrigues', 'Matheus Nachtergaele', 'Leandro Firmino'],
    imdbRating: 8.7,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX200_CR0,0,200,296_AL_.jpg',
    id: 18
  }, {
    title: 'Seven',
    year: '1995',
    genres: ['Crime', 'Drama', 'Mystery'],
    comments: {},
    ratings: {},
    poster: 'MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,319,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT127M',
    releaseDate: '1995-12-25',
    avgRate: 0,
    originalTitle: 'Se7en',
    storyline: 'A film about two homicide detectives\' (Morgan Freeman and (Brad Pitt desperate hunt for a serial killer who justifies his crimes as absolution for the world\'s ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic "John Doe" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer\'s terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer\'s modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...                Written by\nMark Fleetwood <mfleetwo@mail.coin.missouri.edu>',
    actors: ['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,319,500_AL_.jpg',
    id: 19
  }, {
    title: 'När lammen tystnar',
    year: '1991',
    genres: ['Crime', 'Drama', 'Thriller'],
    comments: {},
    ratings: {},
    poster: 'MV5BMTQ2NzkzMDI4OF5BMl5BanBnXkFtZTcwMDA0NzE1NA@@._V1_SY500_CR0,0,333,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT118M',
    releaseDate: '1991-03-22',
    avgRate: 0,
    originalTitle: 'The Silence of the Lambs',
    storyline: 'FBI trainee Clarice Starling works hard to advance her career, including trying to hide or put behind her West Virginia roots, of which if some knew would automatically classify her as being backward or white trash. After graduation, she aspires to work in the agency\'s Behavioral Science Unit under the leadership of Jack Crawford. While she is still a trainee, Crawford does ask her to question Dr. Hannibal Lecter, a psychiatrist imprisoned thus far for eight years in maximum security isolation for being a serial killer, he who cannibalized his victims. Clarice is able to figure out the assignment is to pick Lecter\'s brains to help them solve another serial murder case, that of someone coined by the media as Buffalo Bill who has so far killed five victims, all located in the eastern US, all young women who are slightly overweight especially around the hips, all who were drowned in natural bodies of water, and all who were stripped of large swaths of skin. She also figures that Crawford...                Written by\nHuggo',
    actors: ['Jodie Foster', 'Anthony Hopkins', 'Lawrence A. Bonney'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NzkzMDI4OF5BMl5BanBnXkFtZTcwMDA0NzE1NA@@._V1_SY500_CR0,0,333,500_AL_.jpg',
    id: 20
  }, {
    title: 'Livet är underbart',
    year: '1946',
    genres: ['Drama', 'Family', 'Fantasy'],
    comments: {},
    ratings: {},
    poster: 'MV5BMTMzMzY5NDc4M15BMl5BanBnXkFtZTcwMzc4NjIxNw@@._V1_SY500_CR0,0,334,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT130M',
    releaseDate: '1947-08-04',
    avgRate: 0,
    originalTitle: 'It\'s a Wonderful Life',
    storyline: 'George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George\'s modest building and loan company, which was founded by his generous father. But on Christmas Eve, George\'s Uncle Billy loses the business\'s $8,000 while intending to deposit it in the bank. Potter finds the misplaced money and hides it from Billy. When the bank examiner discovers the shortage later that night, George realizes that he will be held responsible and sent to jail and the company will collapse, finally allowing Potter to take over the town. Thinking of his wife, their young children, and others he loves will be better off with him dead, he contemplates suicide. But the prayers of his loved ones result in a gentle angel named Clarence coming to earth to help George, with the promise of earning his ...                Written by\nalfiehitchie',
    actors: ['James Stewart', 'Donna Reed', 'Lionel Barrymore'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzMzY5NDc4M15BMl5BanBnXkFtZTcwMzc4NjIxNw@@._V1_SY500_CR0,0,334,500_AL_.jpg',
    id: 21
  }, {
    title: 'De misstänkta',
    year: '1995',
    genres: ['Crime', 'Drama', 'Mystery'],
    comments: {},
    ratings: {},
    poster: 'MV5BMzI1MjI5MDQyOV5BMl5BanBnXkFtZTcwNzE4Mjg3NA@@._V1_SY500_CR0,0,333,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT106M',
    releaseDate: '1995-11-03',
    avgRate: 0,
    originalTitle: 'The Usual Suspects',
    storyline: 'Following a truck hijack in New York, five conmen are arrested and brought together for questioning. As none of them are guilty, they plan a revenge operation against the police. The operation goes well, but then the influence of a legendary mastermind criminal called Keyser Söze is felt. It becomes clear that each one of them has wronged Söze at some point and must pay back now. The payback job leaves 27 men dead in a boat explosion, but the real question arises now: Who actually is Keyser Söze?                Written by\nSoumitra',
    actors: ['Kevin Spacey', 'Gabriel Byrne', 'Chazz Palminteri'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzI1MjI5MDQyOV5BMl5BanBnXkFtZTcwNzE4Mjg3NA@@._V1_SY500_CR0,0,333,500_AL_.jpg',
    id: 22
  }, {
    title: 'Livet är underbart',
    year: '1997',
    genres: ['Comedy', 'Drama', 'War'],
    comments: {},
    ratings: {},
    poster: 'MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY500_SX335_AL_.jpg',
    contentRating: '11',
    duration: 'PT116M',
    releaseDate: '1999-01-22',
    avgRate: 0,
    originalTitle: 'La vita è bella',
    storyline: 'In 1930s Italy, a carefree Jewish book keeper named Guido starts a fairy tale life by courting and marrying a lovely woman from a nearby city. Guido and his wife have a son and live happily together until the occupation of Italy by German forces. In an attempt to hold his family together and help his son survive the horrors of a Jewish Concentration Camp, Guido imagines that the Holocaust is a game and that the grand prize for winning is a tank.                Written by\nAnthony Hughes <husnock31@hotmail.com>',
    actors: ['Roberto Benigni', 'Nicoletta Braschi', 'Giorgio Cantarini'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SY500_SX335_AL_.jpg',
    id: 23
  }, {
    title: 'Léon',
    year: '1994',
    genres: ['Crime', 'Drama', 'Thriller'],
    comments: {},
    ratings: {},
    poster: 'MV5BMjdjMGU3MGYtN2Y5ZC00MTE4LWE4YWQtMTBhMjc3MTk0ZDUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_SX332_AL_.jpg',
    contentRating: '15',
    duration: 'PT110M',
    releaseDate: '1995-02-24',
    avgRate: 0,
    originalTitle: '',
    storyline: 'After her father, mother, older sister and little brother are killed by her father\'s employers, the 12-year-old daughter of an abject drug dealer is forced to take refuge in the apartment of a professional hitman who at her request teaches her the methods of his job so she can take her revenge on the corrupt DEA agent who ruined her life by killing her beloved brother.                Written by\nJ. S. Golden',
    actors: ['Jean Reno', 'Gary Oldman', 'Natalie Portman'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjdjMGU3MGYtN2Y5ZC00MTE4LWE4YWQtMTBhMjc3MTk0ZDUwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_SX332_AL_.jpg',
    id: 24
  }, {
    title: 'Spirited Away',
    year: '2001',
    genres: ['Animation', 'Adventure', 'Family'],
    comments: {},
    ratings: {},
    poster: 'MV5BNmU5OTQ0OWQtOTY0OS00Yjg4LWE1NDYtNDRhYWMxYWY4OTMwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,352,500_AL_.jpg',
    contentRating: '7',
    duration: 'PT125M',
    releaseDate: '2003-09-19',
    avgRate: 0,
    originalTitle: 'Sen to Chihiro no kamikakushi',
    storyline: 'Chihiro and her parents are moving to a small Japanese town in the countryside, much to Chihiro\'s dismay. On the way to their new home, Chihiro\'s father makes a wrong turn and drives down a lonely one-lane road which dead-ends in front of a tunnel. Her parents decide to stop the car and explore the area. They go through the tunnel and find an abandoned amusement park on the other side, with its own little town. When her parents see a restaurant with great-smelling food but no staff, they decide to eat and pay later. However, Chihiro refuses to eat and decides to explore the theme park a bit more. She meets a boy named Haku who tells her that Chihiro and her parents are in danger, and they must leave immediately. She runs to the restaurant and finds that her parents have turned into pigs. In addition, the theme park turns out to be a town inhabited by demons, spirits, and evil gods. At the center of the town is a bathhouse where these creatures go to relax. The owner of the bathhouse ...                Written by\nZachary Harper',
    actors: ['Daveigh Chase', 'Suzanne Pleshette', 'Miyu Irino'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BNmU5OTQ0OWQtOTY0OS00Yjg4LWE1NDYtNDRhYWMxYWY4OTMwXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY500_CR0,0,352,500_AL_.jpg',
    id: 25
  }, {
    title: 'Rädda menige Ryan',
    year: '1998',
    genres: ['Drama', 'War'],
    comments: {},
    ratings: {},
    poster: 'MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,339,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT169M',
    releaseDate: '1998-10-09',
    avgRate: 0,
    originalTitle: 'Saving Private Ryan',
    storyline: 'Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt. Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA. Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall, is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men (Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother...                Written by\nJ.Zelman',
    actors: ['Tom Hanks', 'Matt Damon', 'Tom Sizemore'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SY500_CR0,0,339,500_AL_.jpg',
    id: 26
  }, {
    title: 'Harmonica - En hämnare',
    year: '1968',
    genres: ['Western'],
    comments: {},
    ratings: {},
    poster: 'MV5BYjFiOTlmMzgtOGZlYi00NjY0LThmMzEtNmQ0OTgxNGViOTZmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY500_CR0,0,329,500_AL_.jpg',
    contentRating: '15',
    duration: 'PT175M',
    releaseDate: '1969-08-04',
    avgRate: 0,
    originalTitle: 'C\'era una volta il West',
    storyline: 'Story of a young woman, Mrs. McBain, who moves from New Orleans to frontier Utah, on the very edge of the American West. She arrives to find her new husband and family slaughtered, but by whom? The prime suspect, coffee-lover Cheyenne, befriends her and offers to go after the real killer, assassin gang leader Frank, in her honor. He is accompanied by Harmonica, a man already on a quest to get even.                Written by\nDrGoodBeat / edited by statmanjeff',
    actors: ['Henry Fonda', 'Charles Bronson', 'Claudia Cardinale'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BYjFiOTlmMzgtOGZlYi00NjY0LThmMzEtNmQ0OTgxNGViOTZmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY500_CR0,0,329,500_AL_.jpg',
    id: 27
  }, {
    title: 'American History X',
    year: '1998',
    genres: ['Crime', 'Drama'],
    comments: {},
    ratings: {},
    poster: 'MV5BY2E2MWU5ZDktOTQ0OS00NGIzLTg4YTgtYjFhNTRlMjA1NzFjL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SY500_SX340_AL_.jpg',
    contentRating: '15',
    duration: 'PT119M',
    releaseDate: '1999-02-26',
    avgRate: 0,
    originalTitle: '',
    storyline: 'Derek Vineyard is paroled after serving 3 years in prison for brutally killing two black men who tried to break into/steal his truck. Through his brother, Danny Vineyard\'s narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.                Written by\nNitesh D.(nmxpa7@msn.com)',
    actors: ['Edward Norton', 'Edward Furlong', 'Beverly D\'Angelo'],
    imdbRating: 8.6,
    posterurl: 'https://images-na.ssl-images-amazon.com/images/M/MV5BY2E2MWU5ZDktOTQ0OS00NGIzLTg4YTgtYjFhNTRlMjA1NzFjL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SY500_SX340_AL_.jpg',
    id: 28
  }];
  currentUser: string;

  constructor() {
  }

  public get title() {
    return 'Demo';
  }

  public get currentYear() {
    return new Date().getFullYear();
  }

  public getMovies() {
    return this.movies;
  }
}


